### ISSUE TITLE
Add option to omit project output if there is no cmd output

### ISSUE THREAD

**Issue by mikeboiko** [alajmo/mani#17]
**Is your feature request related to a problem? Please describe.**
I would like to be able to run a command on my projects, but only show output for the projects where output isn't blank.
For example, given the following task in `mani.yaml`:
```
tasks:
  git-status:
    desc: show working tree status
    output: table
    parallel: true
    cmd: git status -s
```

I get the following output when I run `mani run git-status -t main`
```
+----------------+--------------+
| Project        | git-status   |
+----------------+--------------+
| HomeAutomation |              |
+----------------+--------------+
| Linux          | ?? test_file |
+----------------+--------------+
| Vim            |              |
+----------------+--------------+
```
I don't want to see HomeAutomation and Vim in the output table because cmd didn't return anything. I want to see this:
```
+----------------+--------------+
| Project        | git-status   |
+----------------+--------------+
| Linux          | ?? test_file |
+----------------+--------------+
```

**Describe the solution you'd like**
I think adding an option in the [output section](https://manicli.com/config#output) would do the trick.
For example, you could call it `printempty` and it could be true by default. I could set it to false for my purposes.

**Additional context**
I just tried this tool today and I'm loving it!
I had written my own solution to the same problem a few years ago, but I like yours much better so I think I will switch over.
Keep up the good work :)

**Comment by alajmo** [comment]
That makes sense, I've been meaning to introduce some more formatting/filtering of the output (like order, coloring, etc.), for instance, if it returns 0 instead of empty, then perhaps you'd want the same result of not having it shown. I'll add an option like that in the next release.

**Comment by mikeboiko** [comment]
Awesome, I like the sound of all these things!

**Comment by alajmo** [comment]
I've added the feature requested. It's available under the `spec` property:

```
specs:
  custom:
    output: table
    parallel: true
    omit_empty: true

tasks:
  git-status:
    desc: show working tree status
    spec: custom
    cmd: git status -s
```

or if you want, you can specify inline in the task. Let me know if there's an issue!
