### ISSUE TITLE
Option to define parameters in projects

### ISSUE THREAD

**Issue by khmarbaise** [alajmo/mani#19]
**Is your feature request related to a problem? Please describe.**
I have a `mani.yaml` with a larger number of repos..as intended. Given a simple brief example:
```
projects:
    p1:
      path: x
      url: https://.../repos/x.git
    p2:
      path: y
      url: https://.../repos/y.git
tasks:
  upd:
    desc: Update all given projects.
    output: text
    commands:
      - name: switch to master
        cmd: git switch master
      - name: pull update
        cmd: git pull --all -p
```
So in general the usage is fine but I have one issue. I have a lot of git repos (200+) but not all using the same naming for the default branch. Some use `main` some use `master` and others use `dev`... so the definition of a task like the above is
not usable for all cases.

**Describe the solution you'd like**
It would be great having a way to define a kind of a parameter for the task something like (just an idea):
```
projects:
    p1:
      path: x
      url: https://.../repos/x.git
      parameters:
        - branch: main
    p2:
      path: y
      url: https://.../repos/y.git
      parameters:
        - branch: master
tasks:
  upd:
    desc: Update all given projects.
    output: text
    commands:
      - name: switch to ${branch}
        cmd: git switch ${branch}
      - name: pull update
        cmd: git pull --all -p
```
Maybe there should be used a different syntax than using `${..}` to separate them from the environment variables given for all tasks via `env:..`...
