### ISSUE TITLE
mani sync does nothing

### ISSUE THREAD

**Issue by mikeboiko** [alajmo/mani#27]
I created a simplified `mani.yaml` file for this example:
```
projects:
  Vim:
    path: ~/Documents/GitRepos/Vim
    url: https://bitbucket.org/mikeboiko/Vim
    # clone: git clone https://bitbucket.org/mikeboiko/MainSynchredible

  AccuTuneDocs:
    path: ~/Documents/GitRepos/AccuTune/Docs
    url: https://github.com/mikeboiko/AccuTuneDocs
    # clone: git clone https://github.com/mikeboiko/AccuTuneDocs
```

When I run `mani -c ~/Documents/GitRepos/Linux/config/mani.yaml sync`, I get no stdout or stderr output.

My git is configured with credential helpers for GitHub and BitBucket, so I don't need to be prompted for credentials.

I should also point out that I'm keeping my `mani.yaml` file inside one of my repos, and not inside the root folder of all the repos. Not sure if this could be causing an issue somehow.

I tried uncommenting the clone lines in each project, but there was still no output and no actions performed.
