### ISSUE TITLE
Allow inclusion of root dir

### ISSUE THREAD

**Issue by emahuni** [alajmo/mani#47]
## Is your feature request related to a problem? Please describe

I have a `nodejs` monorepo  in the root and it generates `node_modules` dir on `yarn install`. So I have created a task that cleans these kind of dirs. The script simply does `rm -rfv node_modules` but I'd like to also include the root dir and remove that said `node_modules` dir.

## Describe the solution you'd like

Allow a built-in tag and target 'root' to include the root dir as well in any operations.

## Additional context

I thought that the targets cwd: true option or -k makes Mani include the root dir wherein the command is ran, but it doesn't do anything.

**Comment by emahuni** [comment]
I have done this:

```yaml
projects:
  root:
    path: ./
    desc: Root directory
    tags: [root]
```

but the above would be great

**Comment by alajmo** [comment]
`cwd` is the current working directory (so if you type `pwd` in the terminal, that's the directory cwd is targeting).

```yaml
projects:
  dashgrid:
    path: frontend/dashgrid
    url: git@github.com/alajmo/dashgrid.git

tasks:
  pwd:
    cmd: pwd
```

So if you stand in `frontend/dashgrid` and run `mani run pwd --cwd`, it will output (targets dashgrid):

```
 Project  | Pwd
----------+-------------------------------------------------------------
 dashgrid | frontend/dashgrid
```

By default the flag `--cwd` is false, if you want it to default to `true`, add the following:
```
targets:
  default:
    # Target current working directory project
    cwd: true
```

Now, for your example, if you want to target the root directory, you can either define the root project path like this:

```yaml
projects:
  root:
    path: .

  dashgrid:
    path: frontend/dashgrid
    url: git@github.com/alajmo/dashgrid.git

tasks:
  rm-modules:
    cmd: rm -rfv node_modules
```

Then run `mani run rm-modules -p root,dashgrid`.

You can also attach targets directly on rm-modules:

```yaml
targets:
  root:
    projects: [root]
    cwd: true

tasks:
  rm-modules:
    target: root
    cmd: rm -rfv node_modules
```

Does that make sense?
