### ISSUE TITLE
mani cd (a way to change to a project's directory)

### ISSUE THREAD

**Issue by emahuni** [alajmo/mani#48]
## Is your feature request related to a problem? Please describe

Ok so I wish there was a way of quickly moving between directories, so that I can do what I want from there without invoking Mani. One of the reasons is shorter commands and the other is the way the output is displayed. Sometimes the output is just modified such that it doesn't make it as legible as it normally is with the original command that's being run.

## Describe the solution you'd like

The solution is very simple, a way to change the current directory to the filter that is resolved by either tags, project or path eg:

given that we have the following projects configured:

```yaml
projects:
  root:
    path: ./
    tags: [root]

  api:
    path: applications/backend/good-api

  plugger:
    path: plugins/plugin-that-we-want
    tags: [lib]

  plog:
    path: plugins/plugin-that-we-want
    tags: [lib]

```

`mani cd -p=api` changes to `./applications/backend/good-api/`

and 

`mani cd -p=plugger` changes to `./plugins/plugin-that-we-want/`

As mentioned, this works with all the filters that mani provides. In the case where there is more than 1 directory that result from the query (eg: `-t=lib`), then it switches to the first hit.

`mani cd` just changes to the root directory

## Additional context

I tried creating tasks that do this, but it seems like Mani changes the directory back to whatever current directory it was in when it was run.
