### ISSUE TITLE
task alias

### ISSUE THREAD

**Issue by emahuni** [alajmo/mani#49]
## Is your feature request related to a problem? Please describe

It'd be useful to have an alias for a task. Such will make it easier to work in a large team and reduce mental migration from tools used in different platforms and environments.

Eg: Windows cmd: `dir`, but in unix it's `ls`

In addition this will also provide a way to invoke the same task in many different ways, avoiding the same mental clash.

## Describe the solution you'd like

```yaml
  build:clean:
    aliases: ['build+clean', 'build-clean', 'clean-build'],
    # next is meant for single aliases
    alias: 'build+clean' 
    desc: clean & build artifacts, which may produce dirs ("dist", "build", ".cache")
    spec: default
    commands:
      - task: rm:build
      - task: build
```

## Additional context

List of tasks would also show these aliases.
