### ISSUE TITLE
nvm: command not found

### ISSUE THREAD

**Issue by walidMahjoub** [alajmo/mani#58]
- [x] I have the latest version of mani
- [x] I have searched through the existing issues

## Info

- OS
  - [ ] Linux
  - [x] Mac OS X
  - [ ] Windows
  - [ ] other

- Shell
  - [ ] Bash
  - [x] Zsh
  - [ ] Fish
  - [ ] Powershell
  - [ ] other

- Version: 0.22.0

## Problem / Steps to reproduce

nvm is already installed on my computer. but when I run `mani -p projectName "nvm -v"`
I get this error: 
```
projectName| sh:nvm:command not found
projectName | exit status 127
```

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/20699649/202477293-be0d8131-d969-429a-ae5e-35c9bfee72fb.png">

**Comment by alajmo** [comment]
Not familiar with nvm, but it seems to require you to load `nvm` in a new shell whenever you want to use it, so this works for me:

```yaml
tasks:
  test:
    cmd: |
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
      nvm
```
