### ISSUE TITLE
Possibility to add multiple remotes?

### ISSUE THREAD

**Issue by tmerse** [alajmo/mani#62]
## Is your feature request related to a problem? Please describe

Sometimes a user may want to use multiple remotes/push to multiple remotes.

## Describe the solution you'd like

One possible solution could be to make the `url` section of `mani.yaml` a list/array, or add a new `remotes` property.
The first entry could be the default remote used for clone.

Updating `.git/config` could happen through some task that runs `git remote add ${remote}`, iterating over `project/remotes` for each respective repo managed by mani.

## Additional context

Thank you for this tool as this looks more modern than myrepos!

**Comment by tmerse** [comment]
This already comes close, but as I mentioned having a way to specify and enumerate some sort of list would make this more clean

```
projects:
  notes:
    path: ./repositories/some_repo
    env:
      remote_name_1: local
      remote_url_1: ssh://user@path/to/my/repo

tasks:
  add_remotes:
    desc: Add additional remotes
    output: text
    cmd: git remote add "${remote_name_1}" "${remote_url_1}"
```

**Comment by alajmo** [comment]
Good idea, not sure which way to go of the proposed options:

1. make the `url` property a string or array, with the first entry being the default remote
2. Adding a new optional property `remote` (array of strings)

I'm thinking of the 2nd option, feels more intuitive and simpler on the implementation side.

The question is still how do we handle existing remotes:

- Should `mani` be the source of truth, so if user adds a remote outside of `mani` and we run  `mani sync`, should we delete the remote? Could perhaps be solved via global property `sync-remote` (which is set to `false` by default). Or simply ignore existing remotes, just check if the remote exists, if not, add it.

**Comment by tmerse** [comment]
Thanks for the reply and sorry for the delay on my side.

> * Should `mani` be the source of truth, so if user adds a remote outside of `mani` and we run  `mani sync`, should we delete the remote? Could perhaps be solved via global property `sync-remote` (which is set to `false` by default). Or simply ignore existing remotes, just check if the remote exists, if not, add it.

This is a very delicate topic. My gut feeling says "never interfere with sth. a user has set manually", so I woul'd never actively delete existing remotes in `.git/config` if they are not defined in mani.

What I would suggest instead is to try to add remotes that are defined in mani and not part of `.git/config`.
If a remote with the same name but a different uri exists, I would inform the user with a message to resolve manually without altering the existing state. Same goes for notifying a user that there are remotes defined inside the config that are not part of `mani.yaml`, so that they are informed and may add those manually to `mani.yaml`.

But this is of course just my subjective opinion of how this could behave.

**Comment by alajmo** [comment]
I've added the ability to sync remotes now as well. For instance:

```yaml
projects:
 mani:
	 url: git@github.com:alajmo/mani
	 remotes:
		another: https://github.com/mani-version-2
```

If there is another remote with the same name, then mani will simply skip it. However, if you run mani with `mani sync --sync-remotes` it will update the current `.git` remote as well. There's also a config option now to change the default (the default is `false`.

```yaml
sync_remotes: true
projects:
 mani:
	 url: git@github.com:alajmo/mani
	 remotes:
		another: https://github.com/mani-version-2
```

Didn't have time now but `sync_remotes` will delete remotes not defined inside `mani` in the future, currently it only updates the existing remote.

**Comment by tmerse** [comment]
Hey, thanks for considering this and the nice implementation.

Unfortunately it does not quite work for me (at least for me on my machine ©)

Given:

``` yaml
  some-repo:
    url: ssh://user@host/repos/somerepo
    path: $HOME/repositories/somerepo
    remotes:
      someremote: git@foo.com/user/somerepo
```

I get:  `error: chdir /home/<user>/repositories/somerepo: no such file or directory` after I run `many sync` (`many sync --sync-remotes` does not help either).

I could discard this happening due to my alias of mani:  `alias mani="cd $GIT_REPOSITORIES/mani/ && mani"`.

```
mani --version

Version: 0.25.0
Commit: e88f231
Date: 2023-06-07T22:04:23Z
```
