### ISSUE TITLE
Exclude projects by tag during sync

### ISSUE THREAD

**Issue by aayushsrivastava** [alajmo/mani#83]
## Is your feature request related to a problem? Please describe
I have a use case where I want to clone all projects except a few.

I thought of a few ways out like tagging all the other projects besides the excluded ones with a particular tag and using this tag during sync. It makes it difficult to maintain the config though since the excluded projects are fewer in number and will remain static in count. Whereas this new tag has to be now added for any new project.

## Describe the solution you'd like
A new flag `--exclude-tags` which ignores the projects with such tags while cloning repositories.

## Additional context
N/A

**Comment by alajmo** [comment]
There's a field you can set on individual projects, named `sync`, which if set to false, will not sync the project.

```
projects:
  pinto:
    path: frontend/pinto
    url: git@github.com:alajmo/pinto
    tags: [dev]
    sync: false
```
