### ISSUE TITLE
Targets to match one tag out of multiple

### ISSUE THREAD

**Issue by mlabbe** [alajmo/mani#85]
## Is your feature request related to a problem? Please describe

I have a project with tag 'a' and a second project with tag 'b'.  Is it possible to create a target with tags where if either 'a' OR 'b' is matched, then the task runs?

```yaml
projects:
  proj_a:
    tags: [a]

  proj_b:
    tags: [b]

targets:
  a_or_b:
    tags: [a, b]

tasks:
  some_task:
    target:
      tags: [a, b]  
```

In this situation, `mani run some_task` says "no targets".  This is because the projects only have one of the two tags. 

## Describe the solution you'd like

Possible solution would be to list multiple targets on a task, and if one is a match, then the task is ran.

## Additional context

Thanks for your time and consideration!
