### ISSUE TITLE
[docs] Indentation for config examples

### ISSUE THREAD

**Issue by jubr** [alajmo/mani#90]
I think the indentation in the [config](https://manicli.com/config/) examples is slightly off now since the last update.

Copy-paste example:
```yaml
# When running the TUI, specifies whether it should reload when the mani config is changed
reload_tui_on_change: false

# List of Projects
projects:
# Project name [required]
pinto:
 # Determines if the project should be synchronized during 'mani sync'
 sync: true

 # Project path relative to the config file
 # Defaults to project name if not specified
 path: frontend/pinto
```

BTW ❤️ @alajmo tnx for this cool tool, soo happy with it!
