### ISSUE TITLE
Filter Command Args like --tags are ignored with 0.30.0

### ISSUE THREAD

**Issue by AnWeber** [alajmo/mani#92]
- [ x] I have the latest version of mani
- [ x] I have searched through the existing issues

## Info
- OS: Linux
- Shell: zsh
 - mani
Version: 0.30.0    
Commit: 54df456   
Date: 2024-12-25T20:33:38Z

## Problem / Steps to reproduce

Executing `mani exec --tags vscode pwd` will run for all projects in mani file. Projects are not filtered. This behaviour changed between v0.25 and v0.30

> mani.yaml
```yaml
targets:
  default:
    all: true
projects:
  asdf-mani:
    path: ./asdf-mani
    tags:
      - asdf
    url: https://github.com/AnWeber/asdf-mani.git
  vscode-mani:
    path: ./vscode-mani
    tags:
      - vscode
    url: https://github.com/AnWeber/vscode-mani.git
```

Steps:
- `mani sync`
- `mani exec --tags vscode -- pwd`

This is because I have explicitly specified `target.default.all=true` in the configuration. As a result, all projects are always executed, no matter what other restrictions/ filter I specify. Reason for this seems to be https://github.com/alajmo/mani/blob/main/core/dao/project.go#L221

I don't even know if I would change the behavior. I wanted to create the ticket more for documentation purposes, so that someone can find the changed behavior more quickly
