### ISSUE TITLE
Envvar defined in task is lost when included as a sub-task

### ISSUE THREAD

**Issue by tbnguyen1407** [alajmo/mani#98]
- [x] I have the latest version of mani
- [ ] I have searched through the existing issues

## Info

- OS
  - [x] Linux
  - [ ] Mac OS X
  - [ ] Windows
  - [ ] other

- Shell
  - [x] Bash
  - [ ] Zsh
  - [ ] Fish
  - [ ] Powershell
  - [ ] other

- Version: 0.30.1

## Problem / Steps to reproduce

Envvar ($ABC) defined in task (task1) is lost when included as a sub-task of another task (task2)

```
~  mani.yaml ~
projects:
  dummy:
    path: .
tasks:
  task1:
    cmd: echo $ABC
    env:
      ABC: def
  task2:
    commands:
      - task: task1
```

```
mani run task1 --all  ## output "def"
mani run task2 --all  ## output ""
```

**Comment by zextrasGiovanniDefacci** [comment]
I believe, this is potential workaround:

```
projects:
  dummy:
    path: .
tasks:
  task1:
    cmd: echo $ABC
    env:
      ABC: def
  task2:
    env:
      PROJECT_NAME: $(basename $PWD)
    commands:
      - cmd: 'mani run --projects="$PROJECT_NAME" task1'
```
